---
- hosts: web
  user: ec2-user

  tasks:
    - name: setup yarn repo
      become: yes
      shell: curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo | tee /etc/yum.repos.d/yarn.repo

    - name: install yarn
      become: yes
      yum:
        name: yarn
        state: installed
