---
- hosts: web
  user: ec2-user

  vars:
    user: ec2-user

  tasks:
    - name: install zsh
      become: yes
      yum : name={{item}} state=installed
      with_items:
          - git
          - zsh


    - name: Clone oh-my-zsh repo
      become: yes
      git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest=/home/{{user}}/.oh-my-zsh

    - name: Set zsh as default shell
      become: yes
      user: name={{user}} shell=/bin/zsh

    - name: Creating new ~/.zshrc
      copy: src=~/.oh-my-zsh/templates/zshrc.zsh-template dest=~/.zshrc
